### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MarlikAlmighty** [yslim/go_pjproject#2]
After

`swig -c++ -go -cgo -intgosize 64 -outcurrentdir -I/usr/local/include /home/user/pjproject-2.9/pjsip-apps/src/swig/pjsua2.i`

I got 

```
/usr/local/include/pjsua2/siptypes.hpp:386: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/siptypes.hpp:556: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/siptypes.hpp:647: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/siptypes.hpp:681: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/media.hpp:61: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/media.hpp:1390: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/call.hpp:265: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/call.hpp:385: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/call.hpp:561: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/endpoint.hpp:131: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/endpoint.hpp:284: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
```

and after i paste it to pjsua2.go

```
#cgo CXXFLAGS: -I/home/user/go/src/pjproject/lib/static/include -g -O2 -Wno-delete-non-virtual-dtor
#cgo LDFLAGS: -L/home/user/go/src/pjproject/lib/applib -L/usr/local/opt/openssl/lib -lpjsua2-x86_64-apple-darwin17.7.0 -lstdc++ -lpjsua-x86_64-apple-darwin17.7.0 -lpjsip-ua-x86_64-apple-darwin17.7.0 -lpjsip-simple-x86_64-apple-darwin17.7.0 -lpjsip-x86_64-apple-darwin17.7.0 -lpjmedia-codec-x86_64-apple-darwin17.7.0 -lpjmedia-x86_64-apple-darwin17.7.0 -lpjmedia-videodev-x86_64-apple-darwin17.7.0 -lpjmedia-audiodev-x86_64-apple-darwin17.7.0 -lpjmedia-x86_64-apple-darwin17.7.0 -lpjnath-x86_64-apple-darwin17.7.0 -lpjlib-util-x86_64-apple-darwin17.7.0 -lsrtp-x86_64-apple-darwin17.7.0 -lresample-x86_64-apple-darwin17.7.0 -lpj-x86_64-apple-darwin17.7.0 -lssl -lcrypto -lm -lpthread -framework Foundation -framework AppKit

#define intgo swig_intgo
typedef void *swig_voidp;
```

and run

```
go clean -cache
go build -x
```

I got a big listing with on end this

```
pjsua2_wrap.cxx:14420:83:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: ‘pj::AudioMedia::AudioMedia()’ is protected within this context
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/pjsua2/endpoint.hpp:27:0,
                 from /usr/local/include/pjsua2.hpp:22,
                 from pjsua2_wrap.cxx:348:
/usr/local/include/pjsua2/media.hpp:298:5: note: declared protected here
     AudioMedia();
     ^~~~~~~~~~
```

**Comment by yslim** [comment]
swig -c++ -go -cgo -intgosize 64 -outcurrentdir -I/usr/local/include /home/marlik/pjproject-2.9/pjsip-apps/src/swig/pjsua2.i

#cgo CXXFLAGS: -I/home/user/go/src/pjproject/lib/static/include -g -O2 -Wno-delete-non-virtual-dtor

#cgo LDFLAGS: -L/home/user/go/src/pjproject/lib/applib

I think that the directory is not correct. 



켜짐 2019년 7월 24일 에서 오전 12:08:35, Marlik Almighty (notifications@github.com) 작성됨:

After

swig -c++ -go -cgo -intgosize 64 -outcurrentdir -I/usr/local/include /home/marlik/pjproject-2.9/pjsip-apps/src/swig/pjsua2.i

I got

/usr/local/include/pjsua2/siptypes.hpp:386: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/siptypes.hpp:556: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/siptypes.hpp:647: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/siptypes.hpp:681: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/media.hpp:61: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/media.hpp:1390: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/call.hpp:265: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/call.hpp:385: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/call.hpp:561: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/endpoint.hpp:131: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
/usr/local/include/pjsua2/endpoint.hpp:284: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'

and after i paste it to pjsua2.go

#cgo CXXFLAGS: -I/home/user/go/src/pjproject/lib/static/include -g -O2 -Wno-delete-non-virtual-dtor
#cgo LDFLAGS: -L/home/user/go/src/pjproject/lib/applib -L/usr/local/opt/openssl/lib -lpjsua2-x86_64-apple-darwin17.7.0 -lstdc++ -lpjsua-x86_64-apple-darwin17.7.0 -lpjsip-ua-x86_64-apple-darwin17.7.0 -lpjsip-simple-x86_64-apple-darwin17.7.0 -lpjsip-x86_64-apple-darwin17.7.0 -lpjmedia-codec-x86_64-apple-darwin17.7.0 -lpjmedia-x86_64-apple-darwin17.7.0 -lpjmedia-videodev-x86_64-apple-darwin17.7.0 -lpjmedia-audiodev-x86_64-apple-darwin17.7.0 -lpjmedia-x86_64-apple-darwin17.7.0 -lpjnath-x86_64-apple-darwin17.7.0 -lpjlib-util-x86_64-apple-darwin17.7.0 -lsrtp-x86_64-apple-darwin17.7.0 -lresample-x86_64-apple-darwin17.7.0 -lpj-x86_64-apple-darwin17.7.0 -lssl -lcrypto -lm -lpthread -framework Foundation -framework AppKit

#define intgo swig_intgo
typedef void *swig_voidp;

and run

go clean -cache
go build -x

I got a big listing? on end this

pjsua2_wrap.cxx:14420:83: required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: ‘pj::AudioMedia::AudioMedia()’ is protected within this context
{ ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/pjsua2/endpoint.hpp:27:0,
from /usr/local/include/pjsua2.hpp:22,
from pjsua2_wrap.cxx:348:
/usr/local/include/pjsua2/media.hpp:298:5: note: declared protected here
AudioMedia();
^~~~~~~~~~

**Comment by MarlikAlmighty** [comment]
Oh, thanks. And which directory will be correct? Your project is located in ~ / go / src / pjproject, and pjsip is installed in the home directory ~ / pjproject-2.9

**Comment by yslim** [comment]
my pjproject src dir is ~/tmp/pjproject-2.7.2
my pjproject installed dir is
   include directory is /Data/apphome/lib/static/include.
   lib directory is /Data/apphome/lib/static/lib and is linked to /Data/apphome/lib/applib.
   (I had compiled pjproject into two libs, one is static and the other is dynamic).

I think, your -I/usr/local/include, CXXFLAGS, LDFLAGS need to be fixed.

**Comment by MarlikAlmighty** [comment]
Thanks, have a nice day!
