### ISSUE TITLE
thank you!!!

### ISSUE THREAD

**Issue by ghost** [yslim/go_pjproject#3]
How can i donate to you? can you give me your paypal or bitcoin?

**Comment by yslim** [comment]
my bitcoin address : 37rDLSAtK6nbgbrMjU4nvR5oMikT2sujch
thank you.

**Comment by ghost** [comment]
Send 0.01 BTC.
https://www.blockchain.com/btc/address/37rDLSAtK6nbgbrMjU4nvR5oMikT2sujch

Maybe you have email, I’m ready to pay for your help in the future if you agree, and thank you.

**Comment by yslim** [comment]
Thank you for your donation.
my email is yslim@mulbul.com.
